name: Build and Deploy

on:
  push:
    branches:
      - main
      - develop
      
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # Step 3: Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore

    # Step 4: Build the application
    - name: Build Solution
      run: dotnet build --no-restore --configuration Release

    # Step 5: Run tests and collect coverage
    - name: Run Tests and Collect Coverage
      run: |
        dotnet test Tests/HackerNewsReader.Application.Tests --collect:"XPlat Code Coverage"
        dotnet test Tests/HackerNewsReader.Domain.Tests --collect:"XPlat Code Coverage"
        dotnet test Tests/HackerNewsReader.Api.Tests --collect:"XPlat Code Coverage"
        dotnet test Tests/HackerNewsReader.Infrastructure.Tests --collect:"XPlat Code Coverage"

    # Step 6: Install ReportGenerator for code coverage
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    # Step 7: Generate coverage report (HTML and LCOV formats)
    - name: Generate Coverage Report
      run: |
        reportgenerator -reports:**/TestResults/*.coverage -targetdir:./coverage -reporttypes:Html;lcov

    # Step 8: Upload Coverage Report as Artifact
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage
        path: ./coverage

  build-and-publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    outputs:
      build_version: ${{ steps.build_version.outputs.build_version }}
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Generate Build Version
      - name: Generate Build Version
        id: build_version
        run: |
          BUILD_VERSION=$(date +%Y%m%d%H%M%S)
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
          echo "build_version=$BUILD_VERSION" >> $GITHUB_OUTPUT

      # Step 4: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 5: Build Docker image with Build Version
      - name: Build Docker image
        run: |
          docker build \
          -t ghcr.io/${{ github.actor }}/hacker-news-reader-api:${{ env.BUILD_VERSION }} \
          -t ghcr.io/${{ github.actor }}/hacker-news-reader-api:latest \
          .

      # Step 6: Push Docker images to GitHub Container Registry
      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ github.actor }}/hacker-news-reader-api:${{ env.BUILD_VERSION }}
          docker push ghcr.io/${{ github.actor }}/hacker-news-reader-api:latest

  # Deploy to Development Environment
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: github.ref_name == 'develop'
    environment: dev
    steps:
      - name: Display Environment Info
        run: echo "Deploying to dev - ${{ needs.build-and-publish.outputs.build_version }} environment..."

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: Update Azure Container App
        run: |
          az containerapp update \
          --name ${{ secrets.CONTAINER_APP }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --image ghcr.io/sumithavenkataswamy/hacker-news-reader-api:${{ needs.build-and-publish.outputs.build_version }} \
          --set registries="ghcr.io=${{ secrets.GHCR_USERNAME }}=${{ secrets.TOKEN }}"

  deploy-test:
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: github.ref_name == 'main'
    environment: test
    steps:
      - name: Display Environment Info
        run: echo "Deploying to test - ${{ needs.build-and-publish.outputs.build_version }} environment..."

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: Update Azure Container App
        run: |
          az containerapp update \
          --name ${{ secrets.CONTAINER_APP }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --image ghcr.io/sumithavenkataswamy/hacker-news-reader-api:${{ needs.build-and-publish.outputs.build_version }} \
          --set registries="ghcr.io=${{ secrets.GHCR_USERNAME }}=${{ secrets.TOKEN }}"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-test
    if: github.ref_name == 'main'
    environment: prod
    steps:
      - name: Display Environment Info
        run: echo "Deploying to test - ${{ needs.build-and-publish.outputs.build_version }} environment..."

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: Update Azure Container App
        run: |
          az containerapp update \
          --name ${{ secrets.CONTAINER_APP }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --image ghcr.io/sumithavenkataswamy/hacker-news-reader-api:${{ needs.build-and-publish.outputs.build_version }} \
          --set registries="ghcr.io=${{ secrets.GHCR_USERNAME }}=${{ secrets.TOKEN }}"